-- MySQL Script generated by MySQL Workbench
-- Sun Dec 28 02:28:56 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tvect_beta
-- -----------------------------------------------------
-- This is the plain english description of the problem we are trying to solve.
DROP SCHEMA IF EXISTS `tvect_beta` ;

-- -----------------------------------------------------
-- Schema tvect_beta
--
-- This is the plain english description of the problem we are trying to solve.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tvect_beta` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tvect_beta` ;

-- -----------------------------------------------------
-- Table `tvect_beta`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`users` (
  `email` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `password` VARCHAR(15) NOT NULL,
  `role` CHAR(1) NOT NULL DEFAULT 'u' COMMENT 'roles:\nu - user\na - author\nd - admin\nc - health contact',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tvect_beta`.`user_locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`user_locations` (
  `email` VARCHAR(255) NOT NULL,
  `rec_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `longit` DOUBLE NOT NULL,
  `lat` DOUBLE NOT NULL,
  PRIMARY KEY (`rec_time`, `email`),
  CONSTRAINT `fk_email`
    FOREIGN KEY (`email`)
    REFERENCES `tvect_beta`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_email_idx` ON `tvect_beta`.`user_locations` (`email` ASC);


-- -----------------------------------------------------
-- Table `tvect_beta`.`diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`diseases` (
  `disease_name` VARCHAR(63) NOT NULL,
  `description` VARCHAR(1023) NOT NULL DEFAULT 'Description being updated.',
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`disease_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tvect_beta`.`user_infections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`user_infections` (
  `email` VARCHAR(255) NOT NULL,
  `disease_name` VARCHAR(63) NOT NULL,
  `infection_start` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sick_date` TIMESTAMP NULL,
  `infection_end` TIMESTAMP NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`email`, `disease_name`, `infection_start`),
  CONSTRAINT `fk_user_infections_users1`
    FOREIGN KEY (`email`)
    REFERENCES `tvect_beta`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_infections_diseases1`
    FOREIGN KEY (`disease_name`)
    REFERENCES `tvect_beta`.`diseases` (`disease_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_user_infections_diseases1_idx` ON `tvect_beta`.`user_infections` (`disease_name` ASC);


-- -----------------------------------------------------
-- Table `tvect_beta`.`regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`regions` (
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `region_name` VARCHAR(63) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(63) NOT NULL,
  `altitude` DOUBLE NULL,
  `radius` DOUBLE NOT NULL DEFAULT .3,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tvect_beta`.`top_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`top_news` (
  `region_name` VARCHAR(63) NULL,
  `news` BLOB NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` VARCHAR(127) NOT NULL,
  `tags` VARCHAR(255) NULL,
  `article_id` INT NOT NULL AUTO_INCREMENT,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `region_id` INT NULL,
  PRIMARY KEY (`article_id`),
  -- CONSTRAINT `fk_region_name`
   -- FOREIGN KEY (`region_name`)
    -- REFERENCES `tvect_beta`.`regions` (`region_name`)
    -- ON DELETE NO ACTION
    -- ON UPDATE NO ACTION,
  CONSTRAINT `fk_region_id`
    FOREIGN KEY (`region_id`)
    REFERENCES `tvect_beta`.`regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_region_id_idx` ON `tvect_beta`.`top_news` (`region_id` ASC);


-- -----------------------------------------------------
-- Table `tvect_beta`.`regions_copy1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`regions_copy1` (
  `left_lat` DOUBLE NOT NULL,
  `left_long` DOUBLE NOT NULL,
  `right_lat` DOUBLE NOT NULL,
  `right_long` DOUBLE NOT NULL,
  `region_name` VARCHAR(63) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(63) NOT NULL,
  `altitude` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `tvect_beta` ;

-- -----------------------------------------------------
-- Placeholder table for view `tvect_beta`.`latest_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tvect_beta`.`latest_location` (`email` INT, `lat` INT, `longit` INT);

-- -----------------------------------------------------
-- View `tvect_beta`.`latest_location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tvect_beta`.`latest_location`;
USE `tvect_beta`;
CREATE  OR REPLACE VIEW `latest_location` AS
SELECT us.email as email, us.lat as lat, us.longit as longit
FROM user_locations as us 
WHERE us.rec_time >= ALL 
  (SELECT sub_us.rec_time FROM user_locations as sub_us
  WHERE us.email=sub_us.email); 
;
CREATE USER 'general' IDENTIFIED BY 'User!#';

GRANT ALTER, INSERT, SELECT, UPDATE ON TABLE `tvect_beta`.`users` TO 'general';
GRANT INSERT, SELECT ON TABLE `tvect_beta`.`user_locations` TO 'general';
GRANT INSERT, SELECT ON TABLE `tvect_beta`.`user_infections` TO 'general';
GRANT SELECT ON TABLE `tvect_beta`.`diseases` TO 'general';
GRANT SELECT ON TABLE `tvect_beta`.`regions` TO 'general';
GRANT SELECT ON TABLE `tvect_beta`.`top_news` TO 'general';
CREATE USER 'author' IDENTIFIED BY 'Author!#';

GRANT ALTER, INSERT, SELECT, UPDATE ON TABLE `tvect_beta`.`users` TO 'author';
GRANT INSERT, SELECT ON TABLE `tvect_beta`.`user_locations` TO 'author';
GRANT INSERT, SELECT ON TABLE `tvect_beta`.`user_infections` TO 'author';
GRANT SELECT ON TABLE `tvect_beta`.`diseases` TO 'author';
GRANT SELECT ON TABLE `tvect_beta`.`regions` TO 'author';
GRANT SELECT ON TABLE `tvect_beta`.`top_news` TO 'author';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
